services:
  - type: web
    name: cybershield-ai
    runtime: python
    plan: free
    buildCommand: ./build.sh
    startCommand: gunicorn config.wsgi:application
    envVars:
      - key: PYTHON_VERSION
        value: 3.13.5
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: false
      - key: DATABASE_URL
        fromDatabase:
          name: cybershield-ai-db
          property: connectionString
      - key: WEB_CONCURRENCY
        value: 2

databases:
  - name: cybershield-ai-db
    plan: free
    databaseName: cybershield
    user: cybershield
