# Generated by Django 6.1.1 on 2026-10-03 18:41

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScanRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scan_type', models.CharField(choices=[('url', 'URL'), ('message', 'Message'), ('password', 'Password')], max_length=20)),
                ('input_value', models.TextField()),
                ('verdict', models.CharField(choices=[('safe', 'Safe'), ('suspicious', 'Suspicious'), ('dangerous', 'Dangerous')], default='safe', max_length=20)),
                ('risk_score', models.IntegerField(default=0)),
                ('reasons', models.JSONField(blank=True, default=list)),
                ('recommendations', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Scan Record',
                'verbose_name_plural': 'Scan Records',
                'ordering': ['-created_at'],
            },
        ),
    ]
